class Event():
    DEATHRATTLE = 'DEATHRATTLE'
    OVERKILL = 'OVERKILL'

    DAMAGE_RECEIVED = 'DAMAGE_RECEIVED'
    BEFORE_ATTACK = 'BEFORE_ATTACK'
    COMBAT_START = 'COMBAT_START'

    MINION_DIED = 'MINION_DIED'
    FRIENDLY_MINION_SUMMONED = 'FRIENDLY_MINION_SUMMONED'
    FRIENDLY_MINION_LOST_DIVINE_SHIELD = 'FRIENDLY_MINION_LOST_DIVINE_SHIELD'
